name: "Update snapshot"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-v1-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test -u

      - name: Commit and push
        run: |
          git config user.email "83044352+jebibot@users.noreply.github.com"
          git config user.name "Jebibot"
          git add -A
          git commit -m "test: update snapshots"
          git push
